name: Check for Website Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create Data Directory
      run: mkdir -p data

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: last-modified-files
        path: data  # Download artifacts to 'data' directory
        if-no-files-found: 'warn'

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python get_maps.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: last-modified-files
        path: data/last_modified_*.txt  # Upload files from 'data' directory
