name: Check for Website Update

on:
  workflow_dispatch: {}  # Allows manual triggering of the workflow.
  schedule:
    - cron: '0 * * * *' # Scheduled to run at the start of every hour

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python your_script_name.py
