name: Check for Website Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6 AM UTC, which is 8 AM Israel Standard Time (UTC+2)

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: last-modified-data
        path: ./last_modified_data.json
      continue-on-error: true

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python get_maps.py

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: last-modified-data
        path: ./last_modified_data.json
